spring:
  datasource:
    url: jdbc:mysql://:3306/law_alarm_service_db
    username: beom
    password: beom1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    org.springframework.batch: INFO
    org.quartz: DEBUG

api:
  domain: http://:8090
  url:
    zoneSearch: /searchZone
